# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('telephone_number', models.CharField(max_length=16)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
            ],
        ),
    ]
