# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-09 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='nick_name',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
